// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using factoryApi.Context;

namespace factoryApi.Migrations
{
    [DbContext(typeof(MasterFactoryContext))]
    [Migration("20191026132743_Master")]
    partial class Master
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("factoryApi.Models.Machine.Machine", b =>
                {
                    b.Property<long>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<long?>("MachineType");

                    b.Property<long?>("ProductionLineId");

                    b.HasKey("MachineId");

                    b.HasIndex("MachineType");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("factoryApi.Models.Machine.MachineType", b =>
                {
                    b.Property<long>("MachineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc");

                    b.HasKey("MachineTypeId");

                    b.ToTable("MachineTypes");
                });

            modelBuilder.Entity("factoryApi.Models.Operation.Operation", b =>
                {
                    b.Property<long>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("OperationTypeId");

                    b.Property<long?>("ToolId");

                    b.HasKey("OperationId");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("ToolId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("factoryApi.Models.Operation.OperationType", b =>
                {
                    b.Property<long>("OperationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationTypeName");

                    b.HasKey("OperationTypeId");

                    b.ToTable("OperationTypes");
                });

            modelBuilder.Entity("factoryApi.Models.Operation.Tool", b =>
                {
                    b.Property<long>("ToolId");

                    b.Property<string>("Desc");

                    b.HasKey("ToolId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("factoryApi.Models.ProductionLine.ProductionLine", b =>
                {
                    b.Property<long>("ProductionLineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductionLineName")
                        .IsRequired();

                    b.HasKey("ProductionLineId");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("factoryApi.Models.Relationships.OperationMachineType", b =>
                {
                    b.Property<long>("OperationId");

                    b.Property<long>("MachineTypeId");

                    b.HasKey("OperationId", "MachineTypeId");

                    b.HasIndex("MachineTypeId");

                    b.ToTable("OperationMachineTypes");
                });

            modelBuilder.Entity("factoryApi.Models.Machine.Machine", b =>
                {
                    b.HasOne("factoryApi.Models.Machine.MachineType", "Type")
                        .WithMany()
                        .HasForeignKey("MachineType");

                    b.HasOne("factoryApi.Models.ProductionLine.ProductionLine", "ProductionLine")
                        .WithMany("MachinesList")
                        .HasForeignKey("ProductionLineId");
                });

            modelBuilder.Entity("factoryApi.Models.Operation.Operation", b =>
                {
                    b.HasOne("factoryApi.Models.Operation.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("OperationTypeId");

                    b.HasOne("factoryApi.Models.Operation.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId");
                });

            modelBuilder.Entity("factoryApi.Models.Relationships.OperationMachineType", b =>
                {
                    b.HasOne("factoryApi.Models.Machine.MachineType", "MachineType")
                        .WithMany("OperationMachineType")
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("factoryApi.Models.Operation.Operation", "Operation")
                        .WithMany("OperationMachineType")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
