// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using productionApi.Context;

namespace productionApi.Migrations
{
    [DbContext(typeof(MasterProductionContext))]
    [Migration("20191213190458_ExecAndSetupTimes")]
    partial class ExecAndSetupTimes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("productionApi.Models.Plan.Operation", b =>
                {
                    b.Property<long>("PlanId");

                    b.Property<long>("OperationId");

                    b.Property<long>("ExecutionTime");

                    b.Property<string>("OperationType");

                    b.Property<long>("SetupTime");

                    b.Property<string>("Tool");

                    b.HasKey("PlanId", "OperationId");

                    b.HasAlternateKey("OperationId", "PlanId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("productionApi.Models.Plan.Plan", b =>
                {
                    b.Property<long>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("productionApi.Models.Product.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("PlanId");

                    b.Property<string>("ProductName");

                    b.HasKey("ProductId");

                    b.HasIndex("PlanId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("productionApi.Models.Plan.Operation", b =>
                {
                    b.HasOne("productionApi.Models.Plan.Plan")
                        .WithMany("OperationList")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("productionApi.Models.Product.Product", b =>
                {
                    b.HasOne("productionApi.Models.Plan.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");
                });
#pragma warning restore 612, 618
        }
    }
}
